VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'javier-lopez/eve-base'
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 2794, host: 2794
  #config.vm.box_url = 'https://atlas.hashicorp.com/javier-lopez/boxes/eve-base'
  config.vm.provision 'shell', path: 'eve_precise32_provision_partial.sh'

  #not idea why vagrant works without this in precise32.box
  #but requires it for the modified image, anyway no time for this
  config.ssh.password = 'vagrant'
end

#  vim: set ts=8 sw=4 tw=0 ft=ruby :
